# Generated by Django 2.0.6 on 2020-10-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document2020-10-28_12-50-16/'),
        ),
    ]
