# Generated by Django 2.0.6 on 2020-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0003_auto_20201102_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-02_18-12-12/'),
        ),
    ]
