# Generated by Django 2.0.6 on 2020-11-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0004_auto_20201102_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-02_18-13-30/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='isbn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='issn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
