# Generated by Django 2.0.6 on 2020-11-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0006_auto_20201102_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-02_18-26-17/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='volume',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
