# Generated by Django 2.0.6 on 2020-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0007_auto_20201102_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-02_19-36-55/'),
        ),
    ]
