# Generated by Django 2.0.6 on 2020-11-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0008_auto_20201102_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='document_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='slrtool.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-19_16-37-32/'),
        ),
    ]
