# Generated by Django 2.0.6 on 2020-11-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0009_auto_20201119_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(default=True)),
                ('q2', models.BooleanField(default=True)),
                ('q3', models.BooleanField(default=True)),
                ('q4', models.BooleanField(default=True)),
                ('q5', models.BooleanField(default=True)),
                ('q6', models.BooleanField(default=True)),
                ('q7', models.BooleanField(default=True)),
                ('q8', models.BooleanField(default=True)),
                ('q9', models.BooleanField(default=True)),
                ('q10', models.BooleanField(default=True)),
                ('q11', models.BooleanField(default=True)),
                ('q12', models.BooleanField(default=True)),
                ('q13', models.BooleanField(default=True)),
                ('q14', models.BooleanField(default=True)),
                ('q15', models.BooleanField(default=True)),
                ('qa_passed', models.BooleanField(default=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-21_18-59-13/'),
        ),
    ]
