# Generated by Django 2.0.6 on 2020-11-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0010_auto_20201121_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityassessment',
            name='paper_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='slrtool.Paper'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-21_18-59-55/'),
        ),
    ]
