# Generated by Django 2.0.6 on 2020-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0011_auto_20201121_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-21_19-38-23/'),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q10',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q11',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q12',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q13',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q14',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q15',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='q9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='qa_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='remarks',
            field=models.CharField(default=False, max_length=1000),
            preserve_default=False,
        ),
    ]
