# Generated by Django 2.0.6 on 2020-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slrtool', '0012_auto_20201121_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/2020-11-21_22-22-50/'),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='remarks',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
